AWSTemplateFormatVersion: '2010-09-09'
Description: Basic Infra - S3 + EC2 + IAM Role

Resources:

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub my-free-tier-bucket-${AWS::AccountId}

  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2S3AccessRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole

  S3Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3AccessPolicy
      Roles:
        - !Ref EC2Role
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:*
            Resource: "*"

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0f58b397bc5c1f2e8  # Amazon Linux (update if needed)
      IamInstanceProfile: !Ref InstanceProfile
      Tags:
        - Key: Name
          Value: FreeTierEC2